basePath: /api
definitions:
  data.CounterResponse:
    properties:
      counter:
        example: 5
        type: integer
      createdAt:
        example: 2022-02-30T12:00:00Z
        type: string
      id:
        example: 60c7c02ea38e3c3c4426c1bd
        type: string
      updatedAt:
        example: 2022-02-30T12:00:00Z
        type: string
    type: object
  data.PatchCounterResponse:
    type: object
  data.PatchModel:
    properties:
      Increase:
        type: boolean
      UpdatedBy:
        type: string
    type: object
  errors.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
externalDocs:
  description: GitHub repository
  url: https://github.com/Steadfastie/gokube
host: localhost:8080
info:
  contact:
    email: alexander.divovich@gmail.com
  title: Swagger for steadfastie/gokube project
  version: "1.0"
paths:
  /counter:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ID of the created counter object
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "404":
          description: Counter not found
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: creates a basic structure of the project
      tags:
      - counter
  /counter/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Counter ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Requested counter
          schema:
            $ref: '#/definitions/data.CounterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "404":
          description: Counter not found
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: retrieves a counter by id from database
      tags:
      - counter
    patch:
      consumes:
      - application/json
      parameters:
      - description: Counter ID
        in: path
        name: id
        required: true
        type: string
      - description: Describe your desires
        in: body
        name: patch
        required: true
        schema:
          $ref: '#/definitions/data.PatchModel'
      produces:
      - application/json
      responses:
        "200":
          description: ID of the created counter object
          schema:
            $ref: '#/definitions/data.PatchCounterResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "404":
          description: Counter not found
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: changes counter value
      tags:
      - counter
  /panic/{type}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Type of panic
        in: path
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/errors.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.HTTPError'
      summary: throws a panic
      tags:
      - panic
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
